name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # buildAndPush:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: login to docker hub
  #     uses: docker/login-action@v1
  #     with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1
  #     id: buildx
  #   - name: Build and Push
  #     uses: docker/build-push-action@v2
  #     id: docker_build
  #     with:
  #         context: ./
  #         file: ./docker-compose.github.yml
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/figureshop:latest
  createEnvFile:
    runs-on: ubuntu-latest
    steps:
      - name: create env file on frontend
        run: |
              cd frontend
              echo "DB_HOST=159.223.44.60
                    DB_PORT=3306
                    DB_USERNAME=root
                    DB_PASSWORD=1234567890
                    DB_NAME=dating_app
                    JWT_SECRET=secretKey
                    PORT=3001
                    CLIENT_URL=http://159.223.61.189:3000
                    REDIS_PORT=6379
                    REDIS_DB_NUMBER=1
                    REDIS_HOST=redis" > .env.production
              ls
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: buildAndPush
  #   steps:
  #     - name: executing remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd /app/Dating-app
  #           docker-compose pull
  #           docker-compose up -d